name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  job1:
    name: 1-Checkout Python Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Display Python Version
        run: python --version
  job2:
    name: 2-Checkout TiDB Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up TiDB v5.3.0
        uses: pingcap/tidb-action@v1.0.0
        with:
          tidb-version: v5.3.0
      - name: Display TiDB Version
        run: tidb-server --version